### ISSUE TITLE
sort-gitconfig: sort color section before color "status"

### ISSUE THREAD

**Issue by SuperSandro2000** [tianon/home#1]
I have the following sorted order right now:

```
[color "status"]
	added = green
	changed = yellow
	untracked = cyan

[color]
	ui = true
```

but I would prefer the following:

```
[color]
	ui = true

[color "status"]
	added = green
	changed = yellow
	untracked = cyan
```

Is this easily possible? Can you maybe point me at the right line to get this? I am a bit overwhelmed by the very long awk command.

Thanks for the great sort command! ❤️

**Comment by tianon** [comment]
> Can you maybe point me at the right line to get this? I am a bit overwhelmed by the very long awk command.

Honestly?  Same. :sweat_smile:

(It's maybe better/worse than just a long awk command, as it's `gawk ... | sort ... | gawk ...`, so there are two separate awk expressions in here :grimacing:  I'm *sure* I could probably do it in one, but man, I really don't want to think too much about that. :sweat_smile:)

The general gist of the algorithm is that the first `gawk` expression converts the input into a line-based file (with a few tricks like number prefixes to handle things that are order dependent like `[include]`), then the actual work is done by `sort -u`, and then we have `gawk` again to convert back into Git format.

So, I think the key for getting the order you're looking for is going to be something in how that first `awk` expression handles `[color]` vs `[color "status"]`:

https://github.com/tianon/home/blob/d2aa290cc0a2847dbf9878d225241a6852cbcc47/bin/sort-gitconfig#L29-L46

**Comment by tianon** [comment]
Actually, looking at it, I *think* it's because `[color]` would sort after `[color ` (because I think ` ` comes before `]`), so to fix this would require that middle `if` to munge the space into something else (and then the later `gawk` to munge it back).

**Comment by tianon** [comment]
I've had some success with the following patch, but I'm not sure whether `|` is really the best choice here (since it is conceivable that `|` is used in a path or key or something):

```diff
diff --git a/bin/sort-gitconfig b/bin/sort-gitconfig
index e6176bb..b9cce6b 100755
--- a/bin/sort-gitconfig
+++ b/bin/sort-gitconfig
@@ -33,6 +33,9 @@ gawk '
 				section = m[0]
 				line = substr(line, length(section) + 1)
 				gsub(/^[[:space:]]+/, "", line)
+
+				# https://github.com/tianon/home/issues/1
+				gsub(/ /, "|", section)
 			}
 
 			if (line) {
@@ -73,7 +76,12 @@ gawk '
 		if (printed) {
 			printf "\n"
 		}
-		printf "%s\n", section
+
+		# https://github.com/tianon/home/issues/1
+		printSection = section
+		gsub(/[|]/, " ", printSection)
+
+		printf "%s\n", printSection
 	}
 
 	{
```

**Comment by SuperSandro2000** [comment]
Thank you so much! The patch works great for me.

**Comment by tianon** [comment]
Neat, thanks for testing! :+1:
