### ISSUE TITLE
git config update for 2.27+

### ISSUE THREAD

**Issue by yosifkit** [tianon/home#2]
Not sure if you want to add one of these to `common` or just make me add it to my own config. If you did, my vote would be for `pull.ff only` since that is best for default/main branches.

https://www.reddit.com/r/git/comments/h7kv0y/git_2270_starts_yelling_during_pull/

```console
$ git version
git version 2.28.0
$ git pull
warning: Pulling without specifying how to reconcile divergent branches is
discouraged. You can squelch this message by running one of the following
commands sometime before your next pull:

  git config pull.rebase false  # merge (the default strategy)
  git config pull.rebase true   # rebase
  git config pull.ff only       # fast-forward only

You can replace "git config" with "git config --global" to set a default
preference for all repositories. You can also pass --rebase, --no-rebase,
or --ff-only on the command line to override the configured default per
invocation.

Already up to date.
```

**Comment by tianon** [comment]
I almost never intentionally create a merge commit via `git pull` (but do so accidentally far too often), so I'm all in favor of adding `pull.ff=only` to the `common` file.

**Comment by SuperSandro2000** [comment]
I am using ``git config pull.rebase true`` since a longer time cause I am working in the same branch on multiple machines for my dotfiles.

**Comment by tianon** [comment]
Yeah, that makes sense -- I use `git pull --rebase` a lot too, but my preference is to do that manually (since I turn on `autoStash` too, which then can potentially make a mess, so I prefer things like "merge" and "rebase" to be explicit instead of implicit).

**Comment by tianon** [comment]
So I guess whether this belongs in `common` or `tianon*` depends on whether `pull.rebase` in a later file will override `pull.ff` earlier. :smile:

**Comment by tianon** [comment]
Also, interesting tidbit from `man git-config`:

>        pull.rebase
>
>            ...
>
>            NOTE: this is a possibly dangerous operation; do not use it unless
>            you understand the implications (see git-rebase(1) for details).

**Comment by tianon** [comment]
My testing seems to imply that they interact in non-obvious ways, so this is going into `tianon`. :smile:
